Added Sdlmixer module (untested)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1209,6 +1209,52 @@ if test "$ttf_ok" = no; then
 fi
 LIBS="$LIBS -lSDLttf"
 
+echo $ac_n "checking for Mix_OpenAudio in -lSDL_mixer""... $ac_c" 1>&6
+echo "configure:1214: checking for Mix_OpenAudio in -lSDL_mixer" >&5
+ac_lib_var=`echo SDL_mixer'_'Mix_OpenAudio | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lSDL_mixer  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1222 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char Mix_OpenAudio();
+
+int main() {
+Mix_OpenAudio()
+; return 0; }
+EOF
+if { (eval echo configure:1233: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  mixer_ok=yes
+else
+  echo "$ac_t""no" 1>&6
+mixer_ok=no
+fi
+
+if test "$mixer_ok" = no; then
+        { echo "configure: error: Cannot find SDL mixer library." 1>&2; exit 1; }
+fi
+LIBS="$LIBS -lSDL_mixer"
+
 
 # Finally create all the generated files
 trap '' 1 2 15
